### ISSUE TITLE
JkImport doesn't allow file dependencies?

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#50]
My build script,
```
@JkImport("path/to/jar.jar")
public class Build extends JkJavaBuild {
    ...
}
```
causes jerkar to throw an exception when it tries to compile the build classes:
```
java.lang.IllegalStateException: This dependency is type of org.jerkar.api.depmanagement.JkFileSystemDependency. Expecting JkModuleDependency.
	at org.jerkar.api.depmanagement.JkScopedDependency.withScopeMapping(JkScopedDependency.java:160)
	at org.jerkar.api.depmanagement.JkDependencies.withDefaultScopeMapping(JkDependencies.java:136)
	at org.jerkar.tool.Project.buildDefDependencies(Project.java:192)
	at org.jerkar.tool.Project.getBuildDefDependencyResolver(Project.java:279)
	at org.jerkar.tool.Project.compile(Project.java:84)
	at org.jerkar.tool.Project.compile(Project.java:72)
	at org.jerkar.tool.Project.execute(Project.java:121)
	at org.jerkar.tool.Main.main(Main.java:32)
```

The docs for `JkImport` annotation says it supports file dependencies, but the code seems to expect only module dependencies.

**Comment by djeang** [comment]
The workaround is to put your lib in build/libs/boot so you won't even need the JkImport.
